### ISSUE TITLE
So how to we actually use this?

### ISSUE THREAD

**Issue by rwjack** [s-knibbs/snapcast-ha-player#4]
Installed via hacs, added the following to the config:

```
media_player:
  - platform: snapcast_player
    host: 127.0.0.1
    start_delay: 1s
```
Snapserver is running as an addon on HA.
Is there any additional configuration required on snapserver?

Here's what I use: https://github.com/rwjack/addon-snapserver-spotify
(I have also made the change locally to expose 4953)

When I go into media, select `snapcast_player`, and try google TTS, I get no output on my snapclient devices.

**Comment by rwjack** [comment]
Am I supposed to add port 4953 as some sort of parameter to the snapserver config?

**Comment by rwjack** [comment]
Snapcast container netstat
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:35167        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:1705            0.0.0.0:*               LISTEN      321/snapserver
tcp        0      0 0.0.0.0:1704            0.0.0.0:*               LISTEN      321/snapserver
tcp        0      0 0.0.0.0:1780            0.0.0.0:*               LISTEN      321/snapserver
tcp        0      0 0.0.0.0:44153           0.0.0.0:*               LISTEN      323/librespot
udp        0      0 127.0.0.11:46867        0.0.0.0:*                           -
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           323/librespot
```

Snapcast config
```
[server]
threads = -1
datadir = /data/snapserver/
[stream]
stream = spotify:///librespot?name=Spotify&username=x&password=x&devicename=HA_Snapcast&bitrate=320&volume=100
stream = tcp://0.0.0.0:4953?name=snap_tts&mode=client
buffer = 1000
codec = flac
send_to_muted = true
sampleformat = 48000:32:2
[http]
enabled = true
bind_to_address = 0.0.0.0
doc_root = /usr/share/snapserver/snapweb/
[tcp]
enabled = true
[logging]
debug = false
```

**Comment by rwjack** [comment]
OK, now I see the new media player as a SNAPWEB source, I see 4953 is exposed and reachable, but still no audio plays...

```
media_player:
  - platform: snapcast_player
    host: hass-ipv4-addr
    start_delay: 1s
```

**Comment by s-knibbs** [comment]
It needs to be `mode=server` to work. Given that you're running locally you'll also be able to use a pipe once I get #3 merged, so the config would be somthing like:

```
media_player:
  - platform: snapcast_player
    host: /path/to/pipe
    start_delay: 1s
```
